In [2]:
import pandas as pd
import numpy as np

In [3]:
people = {

    "first": ["Corey", "Jane", "John", "Chris", np.nan, None, "NA"],
    "last": ["Shafer", "Doe", "Doe", "Shafer", np.nan, np.nan, "Missing"],
    "email": ["CoreyMShafer@gmail.com", "JaneDoe@gmaio.com", "JohnDoe@gmail.com", None, np.nan,"Anonymous@gmail.com", "NA"],
    "age": ["33", "55", "63", "36", None, None, "Missing"]
}

In [13]:
df = pd.DataFrame(people)

# Dealing with the custom missing values

df.replace('NA', np.nan, inplace=True)
df.replace("Missing", np.nan, inplace=True)

In [14]:
df

   first    last                   email   age
0  Corey  Shafer  CoreyMShafer@gmail.com    33
1   Jane     Doe       JaneDoe@gmaio.com    55
2   John     Doe       JohnDoe@gmail.com    63
3  Chris  Shafer                    None    36
4    NaN     NaN                     NaN  None
5   None     NaN     Anonymous@gmail.com  None
6    NaN     NaN                     NaN   NaN

In [15]:
df.dropna()

   first    last                   email age
0  Corey  Shafer  CoreyMShafer@gmail.com  33
1   Jane     Doe       JaneDoe@gmaio.com  55
2   John     Doe       JohnDoe@gmail.com  63

In [16]:
df.dropna(axis='index', how='any')
# axis == index or columns based on you wwant to drop row or column
# how = drop rows with any missing values, since the axis is index
# all = only drop rows with all missing values

   first    last                   email age
0  Corey  Shafer  CoreyMShafer@gmail.com  33
1   Jane     Doe       JaneDoe@gmaio.com  55
2   John     Doe       JohnDoe@gmail.com  63

In [17]:
df.dropna(axis='index', how='all')

   first    last                   email   age
0  Corey  Shafer  CoreyMShafer@gmail.com    33
1   Jane     Doe       JaneDoe@gmaio.com    55
2   John     Doe       JohnDoe@gmail.com    63
3  Chris  Shafer                    None    36
5   None     NaN     Anonymous@gmail.com  None

In [8]:
df.dropna(axis='columns', how='all')

   first     last                   email      age
0  Corey   Shafer  CoreyMShafer@gmail.com       33
1   Jane      Doe       JaneDoe@gmaio.com       55
2   John      Doe       JohnDoe@gmail.com       63
3  Chris   Shafer                    None       36
4    NaN      NaN                     NaN     None
5   None      NaN     Anonymous@gmail.com     None
6     NA  Missing                      NA  Missing

In [9]:
df.dropna(axis='columns', how='any')

Empty DataFrame
Columns: []
Index: [0, 1, 2, 3, 4, 5, 6]

if what we want is - we don't care if there is no first or last names we really want the email, so if no email -> drop the row

In [ ]:
df.dropna(axis="index", how="any", subset=['email'])

   first     last                   email      age
0  Corey   Shafer  CoreyMShafer@gmail.com       33
1   Jane      Doe       JaneDoe@gmaio.com       55
2   John      Doe       JohnDoe@gmail.com       63
5   None      NaN     Anonymous@gmail.com     None
6     NA  Missing                      NA  Missing

As long as either one of the values email or last name is there, we shouldn't drop those rows

In [ ]:
df.dropna(axis='index', how="all", subset=['email', 'last'])
# for permanently change inplace=True

   first     last                   email      age
0  Corey   Shafer  CoreyMShafer@gmail.com       33
1   Jane      Doe       JaneDoe@gmaio.com       55
2   John      Doe       JohnDoe@gmail.com       63
3  Chris   Shafer                    None       36
5   None      NaN     Anonymous@gmail.com     None
6     NA  Missing                      NA  Missing

Dealing with the custom missing values

In [18]:
df.isna()

   first   last  email    age
0  False  False  False  False
1  False  False  False  False
2  False  False  False  False
3  False  False   True  False
4   True   True   True   True
5   True   True  False   True
6   True   True   True   True

Sometimes when we are working wiht numerical values we might have to replace our NA values with a certain fixed value.

In [19]:
df.fillna("MISSING")

     first     last                   email      age
0    Corey   Shafer  CoreyMShafer@gmail.com       33
1     Jane      Doe       JaneDoe@gmaio.com       55
2     John      Doe       JohnDoe@gmail.com       63
3    Chris   Shafer                 MISSING       36
4  MISSING  MISSING                 MISSING  MISSING
5  MISSING  MISSING     Anonymous@gmail.com  MISSING
6  MISSING  MISSING                 MISSING  MISSING

In [ ]:
df.fillna(0)
# inplace=True for permanencexn;lsd;kjowh;

   first    last                   email age
0  Corey  Shafer  CoreyMShafer@gmail.com  33
1   Jane     Doe       JaneDoe@gmaio.com  55
2   John     Doe       JohnDoe@gmail.com  63
3  Chris  Shafer                       0  36
4      0       0                       0   0
5      0       0     Anonymous@gmail.com   0
6      0       0                       0   0

### Casting DataTypes

In [21]:
df

   first    last                   email   age
0  Corey  Shafer  CoreyMShafer@gmail.com    33
1   Jane     Doe       JaneDoe@gmaio.com    55
2   John     Doe       JohnDoe@gmail.com    63
3  Chris  Shafer                    None    36
4    NaN     NaN                     NaN  None
5   None     NaN     Anonymous@gmail.com  None
6    NaN     NaN                     NaN   NaN

In [ ]:
# if we want to find the averge age of the people, the age values are not numbers
# we can check the age type as follows
df.dtypes

first    object
last     object
email    object
age      object
dtype: object

In [ ]:
df['age'].mean()
# if you have NaN values, you have to use float instead of int

TypeError: can only concatenate str (not "int") to str

In [26]:
type(np.nan)

float

In [ ]:
df["age"] = df["age"].astype(int)
# if your columnd didn't have missing values this would work fine
# you have two options here
# 1. Either convert those NaN values to something else like a 0 using fillna
# 2. Cast that column to a float instead

TypeError: int() argument must be a string, a bytes-like object or a real number, not 'NoneType'

In [28]:
df["age"] = df["age"].astype(float)

In [29]:
df.dtypes

first     object
last      object
email     object
age      float64
dtype: object

In [30]:
df['age'].mean()

np.float64(46.75)

If you have an entire dataframe of Numbers

In [ ]:
df.astype() # convert everything all at once.

In [ ]:
# dealing with missing values in csv
na_vals = ['NA', "Missing"]
df = pd.read_csv("../data/survey_results_public.csv", index_col="ResponseId", na_values=na_vals) #ResponseId of the df itself is a unique value
schema_df = pd.read_csv("../data/survey_results_schema.csv", index_col="qname")

In [32]:
pd.set_option("display.max_columns", 85) # by default, to only 20 columns are shown even if there are more than that
pd.set_option("display.max_rows", 100)
pd.set_option("display.max_columns", schema_df.shape[0])
pd.set_option("display.max_rows", schema_df.shape[0])

Interesting problem with casting some values 
Lets say that, we want to calculate the average number of coding experience 
among all of them.

In [33]:
df

,MainBranch,Age,EdLevel,Employment,EmploymentAddl,WorkExp,LearnCodeChoose,LearnCode,LearnCodeAI,AILearnHow,YearsCode,DevType,OrgSize,ICorPM,RemoteWork,PurchaseInfluence,TechEndorseIntro,TechEndorse_1,TechEndorse_2,TechEndorse_3,TechEndorse_4,TechEndorse_5,TechEndorse_6,TechEndorse_7,TechEndorse_8,TechEndorse_9,TechEndorse_13,TechEndorse_13_TEXT,TechOppose_1,TechOppose_2,TechOppose_3,TechOppose_5,TechOppose_7,TechOppose_9,TechOppose_11,TechOppose_13,TechOppose_16,TechOppose_15,TechOppose_15_TEXT,Industry,JobSatPoints_1,JobSatPoints_4,JobSatPoints_5,JobSatPoints_6,JobSatPoints_7,JobSatPoints_8,JobSatPoints_9,JobSatPoints_10,JobSatPoints_11,JobSatPoints_13,JobSatPoints_14,JobSatPoints_15,JobSatPoints_16,JobSatPoints_15_TEXT,AIThreat,NewRole,ToolCountWork,ToolCountPersonal,Country,Currency,CompTotal,LanguageChoice,LanguageHaveWorkedWith,LanguageWantToWorkWith,LanguageAdmired,LanguagesHaveEntry,LanguagesWantEntry,DatabaseChoice,DatabaseHaveWorkedWith,...,OfficeStackAsyncAdmired,OfficeStackHaveEntry,OfficeStackWantEntry,CommPlatformHaveWorkedWith,CommPlatformWantToWorkWith,CommPlatformAdmired,CommPlatformHaveEntr,CommPlatformWantEntr,AIModelsChoice,AIModelsHaveWorkedWith,AIModelsWantToWorkWith,AIModelsAdmired,AIModelsHaveEntry,AIModelsWantEntry,SOAccount,SOVisitFreq,SODuration,SOPartFreq,SO_Dev_Content,SO_Actions_1,SO_Actions_16,SO_Actions_3,SO_Actions_4,SO_Actions_5,SO_Actions_6,SO_Actions_9,SO_Actions_7,SO_Actions_10,SO_Actions_15,SO_Actions_15_TEXT,SOComm,SOFriction,AISelect,AISent,AIAcc,AIComplex,AIToolCurrently partially AI,AIToolDon't plan to use AI for this task,AIToolPlan to partially use AI,AIToolPlan to mostly use AI,AIToolCurrently mostly AI,AIFrustration,AIExplain,AIAgents,AIAgentChange,AIAgent_Uses,AgentUsesGeneral,AIAgentImpactSomewhat agree,AIAgentImpactNeutral,AIAgentImpactSomewhat disagree,AIAgentImpactStrongly agree,AIAgentImpactStrongly disagree,AIAgentChallengesNeutral,AIAgentChallengesSomewhat disagree,AIAgentChallengesStrongly agree,AIAgentChallengesSomewhat agree,AIAgentChallengesStrongly disagree,AIAgentKnowledge,AIAgentKnowWrite,AIAgentOrchestration,AIAgentOrchWrite,AIAgentObserveSecure,AIAgentObsWrite,AIAgentExternal,AIAgentExtWrite,AIHuman,AIOpen,ConvertedCompYearly,JobSat
ResponseId,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,
1,I am a developer by profession,25-34 years old,"Master’s degree (M.A., M.S., M.Eng., MBA, etc.)",Employed,"Caring for dependents (children, elderly, etc.)",8.0,"Yes, I am not new to coding but am learning ne...",Online Courses or Certification (includes all ...,"Yes, I learned how to use AI-enabled tools for...",AI CodeGen tools or AI-enabled apps,14.0,"Developer, mobile",20 to 99 employees,People manager,Remote,"Yes, I influenced the purchase of a substantia...",Work,10.0,7.0,9.0,6.0,3.0,11.0,12.0,1.0,8.0,14.0,NaN,15.0,7.0,8.0,12.0,11.0,1.0,6.0,13.0,3.0,16.0,NaN,Fintech,3.0,9.0,5.0,10.0,12.0,11.0,2.0,6.0,7.0,13.0,14.0,15.0,8.0,NaN,I'm not sure,I have neither consider or transitioned into a...,7.0,3.0,Ukraine,EUR European Euro,52800.0,Yes,Bash/Shell (all shells);Dart;SQL,Dart,Dart,NaN,NaN,Yes,Cloud Firestore;PostgreSQL,...,Markdown File,NaN,NaN,"Stack Overflow;Reddit;GitHub (public projects,...",NaN,NaN,NaN,NaN,Yes,openAI GPT (chatbot models);openAI Image gener...,NaN,NaN,NaN,NaN,Yes,A few times per week,Between 5 and 10 years,I have never participated in Q&A on Stack Over...,NaN,1.0,NaN,6.0,2.0,3.0,7.0,8.0,9.0,11.0,15.0,NaN,Neutral,"Rarely, almost never","Yes, I use AI tools monthly or infrequently",Indifferent,Neither trust nor distrust,Bad at handling complex tasks,Learning about a codebase;Writing code;Search ...,Project planning;Deployment and monitoring;Lea...,Documenting code;Debugging or fixing code;Test...,NaN,NaN,"AI solutions that are almost right, but not quite",No,"Yes, I use AI agents at work monthly or infreq...",Not at all or minimally,Software engineering,NaN,AI agents have increased my productivity.;AI a...,AI agents have helped me automate repetitive t...,NaN,NaN,NaN,I am concerned about the accuracy of the infor...,Integrating AI agents with my existing tools a...,The cost of using certain AI agent platforms i...,NaN,NaN,NaN,NaN,Vertex AI,NaN,NaN,NaN,ChatGPT,NaN,When I don’t trust AI’s answers,"Troubleshooting, profiling, debugging",61256.0,10.0
2,I am a developer by profession,25-34 years old,"Associate degree (A.A., A.S., etc.)",Employed,NaN,2.0,"Yes, I am not new to coding but am learning ne...",Online Courses or Certification (includes all ...,"Yes, I learned how to use AI-enabled tools for...",AI CodeGen tools or AI-enabled apps,10.0,"Developer, back-end",500 to 999 employees,Individual contributor,"Hybrid (some in-person, leans heavy to flexibi...",No,Personal Project,13.0,1.0,2.0,9.0,4.0,3.0,12.0,5.0,7.0,14.0,NaN,14.0,1.0,13.0,10.0,9.0,3.0,4.0,2.0,5.0,15.0,NaN,Retail and Consumer Services,10.0,9.0,12.0,1.0,6.0,2.0,11.0,4.0,7.0,13.0,14.0,15.0,5.0,NaN,I'm not sure,I have transitioned into a new career and/or i...,6.0,5.0,Netherlands,EUR European Euro,90000.0,Yes,Java,Java;Python;Swift,Java,NaN,NaN,Yes,Dynamodb;MongoDB,...,Confluence;GitHub;Jira,NaN,NaN,Stack Overflow;Discord;Reddit;Dev.to;Hacker Ne...,Stack Overflow;Discord;Reddit;Dev.to;Hacker Ne...,Stack Overflow;Discord;Reddit;Dev.to;Hacker Ne...,NaN,NaN,Yes,openAI GPT (chatbot models),openAI GPT (chatbot models),openAI GPT (chatbot models),NaN,NaN,Not sure/can't remember,Multiple times per day,Between 10 and 15 years,"Infrequently, less than once per year",Chat (people);Message Boards;Long-form article...,6.0,NaN,5.0,8.0,2.0,4.0,9.0,10.0,11.0,15.0,NaN,"Yes, somewhat",About half of the time,"Yes, I use AI tools weekly",Indifferent,Neither trust nor distrust,Bad at handling complex tasks,Learning new concepts or technologies,Learning about a codebase;Project planning;Com...,Writing code;Documenting code;Debugging or fix...,NaN,NaN,"AI solutions that are almost right, but not qu...",No,"No, and I don't plan to",Not at all or minimally,NaN,NaN,NaN,NaN,NaN,NaN,NaN,It takes significant time and effort to learn ...,NaN,I am concerned about the accuracy of the infor...,Integrating AI agents with my existing tools a...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,When I don’t trust AI’s answers;When I want to...,All skills. AI is a flop.,104413.0,9.0
3,I am a developer by profession,35-44 years old,"Bachelor’s degree (B.A., B.S., B.Eng., etc.)","Independent contractor, freelancer, or self-em...",None of the above,10.0,"Yes, I am not new to coding but am learning ne...",Online Courses or Certification (includes all ...,"Yes, I learned how to use AI-enabled tools for...",AI CodeGen tools or AI-enabled apps;Technical ...,12.0,"Developer, front-end",NaN,NaN,NaN,No,Work,12.0,2.0,3.0,7.0,5.0,10.0,13.0,1.0,4.0,14.0,NaN,8.0,1.0,2.0,12.0,13.0,3.0,9.0,4.0,11.0,15.0,NaN,Software Development,9.0,11.0,8.0,12.0,1.0,5.0,2.0,4.0,3.0,13.0,14.0,15.0,10.0,NaN,No,I have transitioned into a new career and/or i...,3.0,3.0,Ukraine,UAH Ukrainian hryvnia,2214000.0,Yes,Dart;HTML/CSS;JavaScript;TypeScript,Dart;HTML/CSS;JavaScript;TypeScript,Dart;HTML/CSS;JavaScript;TypeScript,NaN,NaN,Yes,MongoDB;MySQL;PostgreSQL,...,GitHub;GitLab;Jira,NaN,NaN,Stack Overflow;Discord;Dev.to;X;YouTube;LinkedIn,Stack Overflow;Discord;Dev.to;X;YouTube;LinkedIn,Stack Overflow;Discord;Dev.to;X;YouTube;LinkedIn,NaN,NaN,Yes,Gemini (Flash general purpose models);openAI G...,Gemini (Flash general purpose models);Gemini (...,Gemini (Flash general purpose models);openAI G...,NaN,NaN,Not sure/can't remember,A few times per week,Between 5 and 10 years,"Infrequently, less than once per year",Chat (people);Videos;Lists of recommendations ...,3.0,NaN,4.0,5.0,1.0,2.0,7.0,9.0,11.0,15.0,NaN,Neutral,About half of the time,"Yes, I use AI tools daily",Favorable,Somewhat trust,Neither good or bad at handling complex tasks,Documenting code;Debugging or fixing code;Test...,NaN,Project planning;Committing and reviewing code...,Learning about a codebase;Writing code;Generat...,NaN,"AI solutions that are almost right, but not qu...",No,"Yes, I use AI agents at work weekly","Yes, somewhat",Software engineering,Multi-platform search enablement,AI agents have increased my productivity.;AI a...,AI agents have improved the quality of my code...,AI agents have improved collaboration within m...,NaN,NaN,It takes significant time and effort to learn ...,My company's IT and/or InfoSec teams have stri...,NaN,I am concerned about the accuracy of the infor...,NaN,Redis,NaN,NaN,NaN,NaN,NaN,ChatGPT;Claude Code;GitHub Copilot;Google Gemini,NaN,When I don’t trust AI’s answers;When I want to...,"Understand how things actually work, problem s...",53061.0,8.0
4,I am a developer by profession,35-44 years old,"Bachelor’s degree (B.A., B.S., B.Eng., etc.)",Employed,None of the above,4.0,"Yes, I am not new to coding but am learning ne...","Other online resources (e.g. standard search, ...","Yes, I learned how to use AI-enabled tools for...",AI CodeGen tools or AI-enabled apps;Videos (no...,5.0,"Developer, back-end","10,000 or more employees",Individual contributor,Remote,No,Personal Project,2.0,12.0,6.0,5.0,13.0,3.0,8.0,11.0,7.0,14.0,NaN,10.0,5.0,8.0,4.0,13.0,12.0,2.0,7.0,1.0,15.0,NaN,Retail and Consumer Services,1.0,5.0,6.0,7.0,8.0,9.0,10.0,11.0,12.0,13.0,14.0,15.0,3.0,NaN,No,I have neither consider or transitioned into a...,NaN,NaN,Ukraine,EUR European Euro,31200.0,Yes,Java;Kotlin;SQL,Java;Kotlin,Java;Kotlin,NaN,NaN,No,NaN,...,GitLab;Jira,NaN,NaN,Stack Overflow;Reddit;YouTube;LinkedIn,"Stack Overflow;Reddit;GitHub (public projects,...",Stack Overflow;Reddit;YouTube;LinkedIn,NaN,NaN,No,NaN,NaN,NaN,NaN,NaN,Yes,A few times per month or weekly,Between 3 and 5 years,I have never participated in Q&A on Stack Over...,Videos;Chat (bot/AI),1.0,NaN,4.0,5.0,6.0,7.0,8.0,9.0,11.0,15.0,NaN,Neutral,"Rarely, almost never","Yes, I use AI tools weekly",Favorable,Somewhat trust,Bad at handling complex tasks,NaN,Project planning;Documenting code;Testing code...,Learning about a codebase;Writing code;Debuggi...,Search for answers;Generating content or synth...,NaN,"AI solutions that are almost right, but not qu...",NO,"Yes, I use AI agents at work monthly or infreq...",Not at all or minimally,Software engineering,Language processing,AI agents have accelerated my learning about n...,AI agents have increased my productivity.;AI a...,AI agents have helped me automate repetitive t...,NaN,NaN,It takes significant time and effort to learn ...,NaN,I am concerned about the accuracy of the infor...,Integrating AI agents with my existing tools a...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,ChatGPT;Claude Code,NaN,When I don’t trust AI’s answers;When I want to...,NaN,36197.0,6.0
5,I am a developer by profession,35-44 years old,"Master’s degree (M.A., M.S., M.Eng., MBA, etc.)","Independent contractor, freelancer, or self-em...","Caring for dependents (children, elderly, etc.)",21.0,"No, I am not new to coding and did not learn n...",NaN,"Yes, I learned how to use AI-enabled tools for...",Technical documentation (is generated for/by t...,22.0,Engineering manager,NaN,NaN,NaN,"Yes, I endorsed a tool that was open-source an...",Work,6.0,3.0,1.0,9.0,10.0,8.0,7.0,4.0,2.0,14.0,NaN,7.0,13.0,3.0,9.0,12.0,6.0,1.0,8.0,14.0,15.0,NaN,Software Development,9.0,13.0,14.0,8.0,6.0,5.0,7.0,2.0,1.0,12.0,10.0,15.0,3.0,NaN,No,I have neither consider or transitioned into a...,4.0,3.0,Ukraine,USD United States dollar,60000.0,Yes,C;C#;C++;Delphi;HTML/CSS;Java;JavaScript;Lua;P...,C#;Java;JavaScript;Python;SQL;TypeScript,C#;Java;JavaScript;Python;SQL;TypeScript,NaN,NaN,Yes,Elasticsearch;Microsoft SQL Server;MySQL;Oracl...,...,Azure Devops;GitHub;Jira,NaN,NaN,Stack Overflow;Stack Exchange;GitHub (public p...,Stack Overflow;Stack Exchange;GitHub (public p...,Stack Overflow;Stack Exchange;GitHub (public p...,NaN,NaN,Yes,openAI GPT (chatbot models),openAI GPT (chatbot models),openAI GPT (chatbot models),NaN,NaN,No,A few times per month or weekly,Between 5 and 10 years,"Infrequently, less than once per year",Long-form articles,1.0,NaN,7.0,4.0,2.0,5.0,10.0,6.0,12.0,15.0,NaN,"No, not really","Rarely, almost never","Yes, I use AI tools weekly",Favorable,Neither trust nor distrust,"Good, but not great at handling complex tasks",Learning about a codebase;Writing code;Debuggi...,Project planning;Documenting code;Testing code...,Generating content or synthetic data,NaN,NaN,"AI solutions that are almost right, but not quite",partly,"No, and I don't plan to","Yes, to a great extent",NaN,NaN,NaN,NaN,NaN,NaN,NaN,Integrating AI agents with my existing tools a...,NaN,I am concerned about the accuracy of the infor...,It takes significant time and effort to learn ...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,When I don’t trust AI’s answers,"critical thinking, the skill to define the tas...",60000.0,7.0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
49119,I am a developer by profession,25-34 years old,"Bachelor’s degree (B.A., B.S., B.Eng., etc.)",Employed,NaN,9.0,"Yes, I am not new to coding but am learning ne...",Online Courses or Certification (includes all ...,"Yes, I learned how to use AI-enabled tools req...",AI CodeGen tools or AI-enabled apps;Technical ...,13.0,"Developer, full-stack",500 to 999 employees,Individual contributor,"Hybrid (some remote, leans heavy to in-person)",No,Personal Project,8.0,2.0,4.0,5.0,6.0,7.0,9.0,3.0,1.0,10.0,NaN,8.0,2.0,6.0,3.0,9.0,4.0,1.0,5.0,7.0,10.0,NaN,Software Development,11.0,13.0,12.0,10.0,6.0,1.0,9.0,14.0,2.0,8.0,7.0,15.0,3.0,NaN,I'm not sure,I have somewhat considered changing my career ...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,8.0
49120,I am a developer by profession,35-44 years old,"Bachelor’s degree (B.A., B.S., B.Eng., etc.)",Employed,"Caring for dependents (children, elderly, etc.)",13.0,"No, I am not new to coding and did not learn n...",NaN,"Yes, I learned how to use AI-enabled tools req...",AI CodeGen tools or AI-enabled apps;Videos (no...,15.0,"Developer, full-stack","1,000 to 4,999 employees",Individual contributor,"Hybrid (some remote, leans heavy to in-person)","Yes, I endorsed a tool that was open-source an...",NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
49121,I am a developer by profession,25-34 years old,"Secondary school (e.g. American high school, G...",Employed,NaN,2.0,"Yes, I am not new to coding but am learning ne...","Other online resources (e.g. standard search, ...","No, I didn't spend time learning in the past year",NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
49122,I am a developer by profession,25-34 years old,"Associate degree (A.A., A.S., etc.)",Employed,None of the above;Engaged in paid work (20-29 ...,10.0,"No, I am not new to coding and did not learn n...",NaN,"Yes, I learned how to use AI-enabled tools for...",Videos (not associated with specific online co...,14.0,"Developer, full-stack",20 to 99 employees,Individual contributor,"Hybrid (some remote, leans heavy to in-person)","Yes, I influenced the purchase of a substantia...",Work,5.0,6.0,3.0,8.0,1.0,9.0,7.0,4.0,2.0,10.0,NaN,9.0,7.0,8.0,2.0,4.0,6.0,3.0,5.0,1.0,10.0,NaN,Manufacturing,8.0,14.0,11.0,10.0,1.0,2.0,5.0,13.0,7.0,12.0,6.0,15.0,4.0,NaN,No,I have somewhat considered changing my career ...,8.0,2.0,France,EUR European Euro,50000.0,Yes,C#;SQL,C#;HTML/CSS;Java;JavaScript;Kotlin;PHP;Python;...,C#;SQL,Visual FoxPro,NaN,Yes,Microsoft SQL Server;MySQL,...,Asana;GitHub;Obsidian,NaN,NaN,Stack Overflow;Discord;YouTube;LinkedIn,Stack Overflow;Discord;YouTube;LinkedIn,Stack Overflow;Discord;YouTube;LinkedIn,NaN,NaN,No,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,"Yes, I use AI tools daily",Favorable,Somewhat distrust,Bad at handling complex tasks,Writing code;Documenting code;Generating conte...,Debugging or fixing code;Testing code;Committi...,Project planning,NaN,Learning about a codebase;Search for answers;L...,"AI solutions that are almost right, but not qu...","no, IA do not control de code part, it's essen...","No, I use AI exclusively in copilot/autocomple...",Not at all or minimally,Marketing,Multi-platform search enablement;Language proc...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,7.0
49123,I am a developer by profession,25-34 years old,Some college/university study without earning ...,Employed,None of the above,10.0,"No, I am not new to coding and did not learn n...",NaN,"No, I learned something that was not related t...",NaN,15.0,"Developer, full-stack",Less than 20 employees,Individual contributor,"Your choice (very flexible, you can come in wh...","Yes, I influenced the purchase of a substantia...",Personal Project,9.0,2.0,3.0,1.0,6.0,4.0,7.0,5.0,8.0,10.0,NaN,8.0,1.0,7.0,5.0,6.0,2.0,3.0,4.0,9.0,10.0,NaN,Software Development,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,No,I have somewhat considered changing my career ...,NaN,NaN,Italy,EUR European Euro,40000.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,8.0

In [35]:
df['YearsCode'].head(10)

ResponseId
1     14.0
2     10.0
3     12.0
4      5.0
5     22.0
6     20.0
7     13.0
8     30.0
9     15.0
10    10.0
Name: YearsCode, dtype: float64

In [36]:
df["YearsCode"].mean()

np.float64(16.57525581395349)

In [37]:
df["YearsCode"].astype(float)

ResponseId
1        14.0
2        10.0
3        12.0
4         5.0
5        22.0
         ...
49119    13.0
49120    15.0
49121     NaN
49122    14.0
49123    15.0
Name: YearsCode, Length: 49123, dtype: float64

In [ ]:
# view unique value of a series
df["YearsCode"].unique()

array([ 14.,  10.,  12.,   5.,  22.,  20.,  13.,  30.,  15.,   9.,   6.,
        nan,   3.,  40.,   8.,  45.,  35.,  11.,   7.,  47.,  41.,  36.,
        23.,  29.,  26.,  25.,  38.,  21.,  19.,  18.,  16.,   4.,  17.,
        42.,  27.,  24.,   2.,  28.,  37.,  32.,   1.,  39.,  53.,  33.,
        50.,  48.,  44.,  31.,  46.,  43.,  49.,  52.,  34.,  51.,  58.,
        57.,  54.,  63.,  60.,  55.,  65., 100.,  99.,  56.,  69.,  90.,
        61.,  67.,  75.,  64.,  98.,  68.,  89.,  62.,  78.,  70.,  76.,
        82.,  59.])

In [39]:
df["YearsCode"].median()

np.float64(14.0)